#!/usr/bin/python
# -*- coding: utf-8 -*-

"""

Connect to the REST API of a Noark 5 service to
export, import or verify Noark 5 archive files.

"""

# $Id$
#
# noark5-parser (Python)
#
# Copyright (C) 2018  Ole Aamot
#
# Authors: Ole Aamot <ole@aamot.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
program = "noark5"
version = "0.1.0 (2018-11-14)"
git_url = "https://github.com/oleaamot/noark5-parser.git"

import sys
import inspect
sys.path.append('lib')
import argparse
import datetime
from hashlib import sha256
import json
import mechanize
import os
import re
from subprocess import call
import urllib2
import urlparse
import xml.etree.ElementTree

noarkrelbase = 'http://rel.kxml.no/noark5/v4/api/'
nikitarelbase = 'http://nikita.arkivlab.no/noark5/v4/'

class Noark5Parser:
        knownrels = [
        noarkrelbase + 'admin/administrativenhet/',
        noarkrelbase + 'admin/bruker/',
        noarkrelbase + 'admin/enhet/',
        noarkrelbase + 'admin/ny-administrativenhet/',
        noarkrelbase + 'admin/ny-bruker/',
        noarkrelbase + 'admin/ny-rettighet/',
        noarkrelbase + 'admin/rettighet/',
        noarkrelbase + 'arkivstruktur/',
        noarkrelbase + 'arkivstruktur/arkiv/',
        noarkrelbase + 'arkivstruktur/arkivdel/',
        noarkrelbase + 'arkivstruktur/arkivskaper/',
        noarkrelbase + 'arkivstruktur/basisregistrering/',
        noarkrelbase + 'arkivstruktur/bygning/',
        noarkrelbase + 'arkivstruktur/dokumentbeskrivelse/',
        noarkrelbase + 'arkivstruktur/dokumentobjekt/',
        noarkrelbase + 'arkivstruktur/elektronisksignatur/',
        noarkrelbase + 'arkivstruktur/fil/',
        noarkrelbase + 'arkivstruktur/hendelseslogg/',
        noarkrelbase + 'arkivstruktur/klasse/',
        noarkrelbase + 'arkivstruktur/klassifikasjonssystem/',
        noarkrelbase + 'arkivstruktur/konvertering/',
        noarkrelbase + 'arkivstruktur/kryssreferanse/',
        noarkrelbase + 'arkivstruktur/logg/',
        noarkrelbase + 'arkivstruktur/mappe/',
        noarkrelbase + 'arkivstruktur/matrikkel/',
        noarkrelbase + 'arkivstruktur/merknad/',
        noarkrelbase + 'arkivstruktur/nasjonaleidentifikator/',
        noarkrelbase + 'arkivstruktur/nasjonalidentifikator/',
        noarkrelbase + 'arkivstruktur/ny-arkiv/',
        noarkrelbase + 'arkivstruktur/ny-arkivdel/',
        noarkrelbase + 'arkivstruktur/ny-arkivskaper/',
        noarkrelbase + 'arkivstruktur/ny-basisregistrering/',
        noarkrelbase + 'arkivstruktur/ny-bygning/',
        noarkrelbase + 'arkivstruktur/ny-dokumentbeskrivelse/',
        noarkrelbase + 'arkivstruktur/ny-dokumentobjekt/',
        noarkrelbase + 'arkivstruktur/ny-elektronisksignatur/',
        noarkrelbase + 'arkivstruktur/ny-hendelseslogg/',
        noarkrelbase + 'arkivstruktur/ny-klasse/',
        noarkrelbase + 'arkivstruktur/ny-klassifikasjonssystem/',
        noarkrelbase + 'arkivstruktur/ny-konvertering/',
        noarkrelbase + 'arkivstruktur/ny-kryssreferanse/',
        noarkrelbase + 'arkivstruktur/ny-mappe/',
        noarkrelbase + 'arkivstruktur/ny-matrikkel/',
        noarkrelbase + 'arkivstruktur/ny-merknad/',
        noarkrelbase + 'arkivstruktur/ny-nasjonalidentifikator',
        noarkrelbase + 'arkivstruktur/ny-plan/',
        noarkrelbase + 'arkivstruktur/ny-posisjon/',
        noarkrelbase + 'arkivstruktur/ny-registrering/',
        noarkrelbase + 'arkivstruktur/plan/',
        noarkrelbase + 'arkivstruktur/posisjon/',
        noarkrelbase + 'arkivstruktur/registrering/',
        noarkrelbase + 'arkivstruktur/sekundaerklassifikasjons',
        noarkrelbase + 'arkivstruktur/underarkiv/',
        noarkrelbase + 'arkivstruktur/underklasse/',
        noarkrelbase + 'arkivstruktur/undermappe/',
        noarkrelbase + 'loggingogsporing/endringslogg/',
        noarkrelbase + 'loggingogsporing/ny-endringslogg/',
        noarkrelbase + 'metadata/arkivdelstatus/',
        noarkrelbase + 'metadata/arkivstatus/',
        noarkrelbase + 'metadata/avskrivningsmaate/',
        noarkrelbase + 'metadata/dokumentmedium/',
        noarkrelbase + 'metadata/dokumentstatus/',
        noarkrelbase + 'metadata/dokumenttype/',
        noarkrelbase + 'metadata/elektronisksignatursikkerhetsnivaa/',
        noarkrelbase + 'metadata/elektronisksignaturverifisert/',
        noarkrelbase + 'metadata/flytstatus/',
        noarkrelbase + 'metadata/format/',
        noarkrelbase + 'metadata/graderingskode/',
        noarkrelbase + 'metadata/hendelsetype/',
        noarkrelbase + 'metadata/journalposttype/',
        noarkrelbase + 'metadata/journalstatus/',
        noarkrelbase + 'metadata/kassasjonsvedtak/',
        noarkrelbase + 'metadata/klassifikasjonstype/',
        noarkrelbase + 'metadata/korrespondanseparttype/',
        noarkrelbase + 'metadata/land/',
        noarkrelbase + 'metadata/mappetype/',
        noarkrelbase + 'metadata/merknadstype/',
        noarkrelbase + 'metadata/moetedeltakerfunksjon/',
        noarkrelbase + 'metadata/moeteregistreringsstatus/',
        noarkrelbase + 'metadata/moeteregistreringstype/',
        noarkrelbase + 'metadata/moetesakstype/',
        noarkrelbase + 'metadata/postnummer/',
        noarkrelbase + 'metadata/presedensstatus/',
        noarkrelbase + 'metadata/sakspartrolle/',
        noarkrelbase + 'metadata/saksstatus/',
        noarkrelbase + 'metadata/skjermingdokument/',
        noarkrelbase + 'metadata/skjermingmetadata/',
        noarkrelbase + 'metadata/slettingstype/',
        noarkrelbase + 'metadata/tilgangskategori/',
        noarkrelbase + 'metadata/tilgangsrestriksjon/',
        noarkrelbase + 'metadata/tilknyttetregistreringsom/',
        noarkrelbase + 'metadata/variantformat/',
        noarkrelbase + 'sakarkiv/',
        noarkrelbase + 'sakarkiv/avskrivning/',
        noarkrelbase + 'sakarkiv/dokumentflyt/',
        noarkrelbase + 'sakarkiv/enkeladresse/',
        noarkrelbase + 'sakarkiv/journalpost/',
        noarkrelbase + 'sakarkiv/kontaktinformasjon/',
        noarkrelbase + 'sakarkiv/korrespondansepart/',
        noarkrelbase + 'sakarkiv/korrespondansepartenhet/',
        noarkrelbase + 'sakarkiv/korrespondansepartintern/',
        noarkrelbase + 'sakarkiv/korrespondansepartperson/',
        noarkrelbase + 'sakarkiv/ny-avskrivning/',
        noarkrelbase + 'sakarkiv/ny-dokumentflyt/',
        noarkrelbase + 'sakarkiv/ny-enkeladresse/',
        noarkrelbase + 'sakarkiv/ny-journalpost/',
        noarkrelbase + 'sakarkiv/ny-kontaktinformasjon/',
        noarkrelbase + 'sakarkiv/ny-korrespondansepart/',
        noarkrelbase + 'sakarkiv/ny-korrespondansepartenhet/',
        noarkrelbase + 'sakarkiv/ny-korrespondansepartintern/',
        noarkrelbase + 'sakarkiv/ny-korrespondansepartperson/',
        noarkrelbase + 'sakarkiv/ny-presedens/',
        noarkrelbase + 'sakarkiv/ny-saksmappe/',
        noarkrelbase + 'sakarkiv/ny-sakspart/',
        noarkrelbase + 'sakarkiv/ny-sakspartenhet/',
        noarkrelbase + 'sakarkiv/ny-sakspartperson/',
        noarkrelbase + 'sakarkiv/presedens/',
        noarkrelbase + 'sakarkiv/sak/',
        noarkrelbase + 'sakarkiv/saksmappe/',
        noarkrelbase + 'sakarkiv/sakspart/',
        noarkrelbase + 'sakarkiv/sakspartenhet/',
        noarkrelbase + 'sakarkiv/saksparter/',
        noarkrelbase + 'sakarkiv/sakspartperson/',
        noarkrelbase + 'sakarkiv/sekundaerklassifikasjon/',
        'self',
    ]
        def __init__(self):
                baseurl = 'http://localhost:8092/noark5v4/'
                filename = 'arkivstruktur.xml'
                username = 'admin@localhost';
                password = 'password';
                refurl = 'http://n5test.kxml.no/api/'
                parser = argparse.ArgumentParser()
                parser.add_argument("--baseurl", help="(default is %s)" % baseurl)
                parser.add_argument("--filename", help="(default is %s)" % filename)
                parser.add_argument("--username", help="(default is %s)" % username)
                parser.add_argument("--password", help="(default is %s)" % password)
                parser.add_argument("--reference", help="set baseurl to to demo API site (override --baseurl)",
                action="store_true")
                parser.add_argument("--verbose", help="enable debug output",
                                    action="store_true")
                parser.add_argument("--keep", help="do not delete created objects",
                                    action="store_true")
                args = parser.parse_args()
                if args.reference:
                        args.baseurl = refurl
                        if args.baseurl:
                                self.baseurl = args.baseurl
                        if args.filename:
                                self.filename = args.filename
                        if args.username:
                                self.username = args.username
                        if args.password:
                                self.password = args.password
                        else:
                                self.baseurl = baseurl
                                self.created = []
                                self.verbose = args.verbose
                                self.keeptestdata = args.keep
                                self.failures = {}
                                self.xfailures = {}
                                self.successes = {}
                print ('BASEURL:' + args.baseurl)
                print ('FILE:' + args.filename)
                print ('USERNAME:' + args.username)
                print ('PASSWORD:' + args.password)

        def noark5_export(self):
                print ('noark5-parser' + ' ' + version + ' ' + git_url)
                print ('\nExporting Noark 5 structure from network to disk...')

        def noark5_import(self):
                print ('noark5-parser' + ' ' + version + ' ' + git_url)
                print ('\nImporting Noark 5 structure from disk to network...')

        def noark5_verify(self):
                print ('noark5-parser' + ' ' + version + ' ' + git_url)
                print ('\nVerifying Noark 5 structure on disk from network...')

if __name__ == '__main__':
  t = Noark5Parser()
  stack = inspect.stack()
  for s in stack:
    if s[1] == "./noark5-export":
      t.noark5_export
    if s[1] == "./noark5-import":
      t.noark5_import
    if s[1] == "./noark5-verify":
      t.noark5_verify
exit()
