#!/bin/bash

# $id$
#
# noark5-parser
#
# Copyright (C) 2017  Ole Aamot
#
# Author: Ole Aamot <oka@oka.no>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

type php >/dev/null 2>&1 || { echo >&2 "runparser requires php, but it's not installed.  Run 'apt-get install php7.1-cli' to install it."; exit 1; }

php noark5-export.php arkivstruktur.xml http://linux:8092/noark5v4/ admin password
