#!/bin/bash

# $id$
#
# noark5-parser
#
# Copyright (C) 2017  Thomas Sødring
# Copyright (C) 2017  Ole Aamot
#
# Author: Ole Aamot <oka@oka.no>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-
# 1301 USA.

wget -q -O arkivstruktur.xml https://raw.githubusercontent.com/KDRS-SA/noark5-validator/master/src/resources/test-uttrekk/uttrekk1/n5uttrekk/arkivstruktur.xml
php noark5-parser.php arkivstruktur.xml http://localhost:8092/noark5v4/ admin password
wget -q -O loependeJournal.xml https://raw.githubusercontent.com/KDRS-SA/noark5-validator/master/src/resources/test-uttrekk/uttrekk1/n5uttrekk/loependeJournal.xml
wget -q -O offentligJournal.xml https://raw.githubusercontent.com/KDRS-SA/noark5-validator/master/src/resources/test-uttrekk/uttrekk1/n5uttrekk/offentligJournal.xml
wget -q -O endringslogg.xml https://raw.githubusercontent.com/KDRS-SA/noark5-validator/master/src/resources/test-uttrekk/uttrekk1/n5uttrekk/endringslogg.xml

wget -q -O arkivverket-arkivstruktur.xml https://raw.githubusercontent.com/arkivverket/arkade5/master/src/Arkivverket.Arkade.Test/TestData/Noark5/ContentClassificationSystem/arkivstruktur.xml
php noark5-parser.php arkivverket-arkivstruktur.xml http://localhost:8092/noark5v4/ admin password

#wget -q -O SesamResearch-arkivstruktur.xml https://raw.githubusercontent.com/SesamResearch/Records-Management-and-Archive-Systems-Research/master/samples/arkivstruktur.xml
#php noark5-parser.php SesamResearch-arkivstruktur.xml http://localhost:8092/noark5v4/ admin password
